routes/web.php
<?php


use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//admin panel
Route::resource('/buses' , 'BusController');

Route::get('/', 'HomeController@index');

Route::post('/tickets', 'HomeController@ticket');

Route::post('/cancel', 'HomeController@cancel');

app/Bus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bus extends Model
{

    protected $fillable =[
        'type' , 'origin' , 'goal' , 'seat' ,'move_date' , 'move_time' , 'cost',
    ];

    public function tickets()
    {
        return $this->hasMany(Ticket::class, 'bus_id');
    }

}

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    protected $fillable = [
        'bus_id','name' , 'family_name' , 'phone_number' , 'seat_number' ,'ticket_number'
    ];


    public function buses()
    {
        return $this->belongsTo(Bus::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BusController.php
<?php

namespace App\Http\Controllers;


use App\Bus;
use App\Http\Requests\BusRequest;


class BusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $buses = Bus::latest()->paginate(10);
        return view('Admin.all' , compact('buses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BusRequest $request)
    {
        Bus::create($request->all());

        return redirect(route('buses.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Bus  $bus
     * @return \Illuminate\Http\Response
     */
    public function show(Bus $bus)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Bus  $bus
     * @return \Illuminate\Http\Response
     */
    public function edit(Bus $bus)
    {
        return view('Admin.edit' , compact('bus'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param BusRequest $request
     * @param \App\Bus $bus
     * @return \Illuminate\Http\Response
     */
    public function update(BusRequest $request, Bus $bus)
    {
        $bus->update($request->all());

        return redirect(route('buses.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Bus  $bus
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bus $bus)
    {
        $bus->delete();
        return redirect(route('buses.index'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;



use App\Bus;
use App\Http\Requests\CancelRequest;
use App\Http\Requests\TicketRequest;
use App\Ticket;



class HomeController extends Controller
{
    public function index()
    {
        $buses = Bus::orderBy('move_date')->get();
        return view('index' , compact('buses'));
    }

    public function ticket(TicketRequest $request)
    {
        //create ticket
        $bus = Bus::find($request->bus_id);

        $reserve = 0;
        for ($i = 0 ; $i < count($bus->tickets); $i++){

            if ($bus->tickets[$i]['status'] == 1){
                $reserve += $bus->tickets[$i]['seat_number'];
            }
        }

        if ($bus->seat - $reserve >= $request->seat_number)
        {
            $substr = substr($request->phone_number, 4, 5 );
            $code =rand(1000,10000);
            $substr.=$code;
            $code = ['ticket_number' => $substr];
            Ticket::create(array_merge($request->all() , $code));

        }else{
            $message = 'متاسفانه تعداد بلیط درخواستی شما بیش از ظرفیت اتوبوس می باشد، لطفا اتوبوس دیگری را انتخاب نمایید';
            return view('alert' , compact('message'));
        }


        return view('ticket' , compact('bus' , 'request' , 'code'));
    }

    public function cancel(CancelRequest $request)
    {
        $ticket = Ticket::whereTicket_number($request->ticket_number)->wherePhone_number($request->phone_number)->first();
        if (is_null($ticket)){
            $message = 'بلیطی با این مشخصات یافت نشد';
            return view('alert' , compact('message'));

        }else{
            if ($ticket->status == 1){
                $ticket->status = 0;
                $ticket->save();

                $message = 'بلیط شما با موفیت حذف شد';
                return view('alert' , compact('message'));
            }else{
                $message = 'بلیط با این مشخصات قبلا کنسل شده است.';
                return view('alert' , compact('message'));
            }

        }

    }

}

resources/views/Admin/all.blade.php
@extends('master')

@section('content')

    <div class="main">
        <div class="page-header head-section">

            <div class="d-flex my-3">
                <h2>اتوبوس ها</h2>
                <a href="{{ route('buses.create') }}" class="btn btn-primary mr-auto">افزودن اتوبوس</a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>نوع اتوبوس</th>
                    <th>مبدا</th>
                    <th>مقصد</th>
                    <th>تاریخ حرکت</th>
                    <th>ساعت حرکت</th>
                    <th>ظرفیت</th>
                    <th>تنظیمات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($buses as $bus)
                    <tr>
                        <td>{{ $bus->type }}</td>
                        <td>{{ $bus->origin }}</td>
                        <td>{{ $bus->goal }}</td>
                        <td>{{ $bus->move_date }}</td>
                        <td>{{ $bus->move_time }}</td>
                        <td>{{ $bus->seat }}</td>
                        <td>
                            <form action="{{ route('buses.destroy'  , $bus->id) }}" method="post">
                                {{ method_field('delete') }}
                                {{ csrf_field() }}
                                <div class="btn-group btn-group-xs" dir="ltr">
                                    <button type="submit" class="btn btn-danger">حذف</button>
                                    <a href="{{ route('buses.edit' , $bus->id) }}" class="btn btn-primary">ویرایش</a>
                                </div>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div style="text-align: center">
            {!! $buses->render() !!}
        </div>
    </div>

@endsection

resources/views/Admin/create.blade.php
@extends('master')

@section('content')

    <div class="main">
        <div class="page-header head-section mt-3">
            <h2>مشخصات سفر</h2>
        </div>
        <form class="form-horizontal" action="{{ route('buses.store') }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            @include('Admin.errors')

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label for="type" class="control-label">نوع اتوبوس</label>
                            <select name="type" id="type" class="form-control">
                                <option selected>VIP</option>
                                <option >اسکانیا</option>
                                <option >معمولی</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label for="origin" class="control-label">مبدا</label>
                            <input type="text" class="form-control" name="origin" id="origin" placeholder="مبدا را وارد کنید" value="{{ old('origin') }}">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label for="goal" class="control-label">مقصد</label>
                            <input type="text" class="form-control" name="goal" id="goal" placeholder="مقصد را وارد کنید" value="{{ old('goal') }}">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label for="move_date" class="control-label">تاریخ حرکت</label>
                            <input type="date" class="form-control" name="move_date" id="move_date" placeholder="تاریخ را وارد کنید" value="{{ old('move_date') }}">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label for="move_time" class="control-label">ساعت حرکت</label>
                            <input type="time" class="form-control" name="move_time" id="move_time" placeholder="ساعت حرکت را وارد کنید" value="{{ old('move_time') }}">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label for="seat" class="control-label">ظرفیت(نفر) </label>
                            <input type="number" class="form-control" name="seat" id="seat" placeholder="ظرفیت اتوبوس را وارد کنید" value="{{ old('seat') }}">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label for="cost" class="control-label">مبلغ</label>
                            <input type="number" class="form-control" name="cost" id="cost" placeholder="مبلغ را وارد کنید" value="{{ old('cost') }}">
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-danger">ایجاد</button>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>


@endsection

resources/views/Admin/edit.blade.php
@extends('master')

@section('content')

    <div class="main">
        <div class="page-header head-section mt-3">
            <h2>ویرایش مشخصات سفر</h2>
        </div>
        <form class="form-horizontal" action="{{ route('buses.update' , $bus->id) }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}

            @include('Admin.errors')
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label for="type" class="control-label">نوع اتوبوس</label>
                            <select name="type" id="type" class="form-control">
                                <option selected>VIP</option>
                                <option >اسکانیا</option>
                                <option >معمولی</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label for="origin" class="control-label">مبدا</label>
                            <input type="text" class="form-control" name="origin" id="origin" placeholder="مبدا را وارد کنید" value="{{ $bus->origin }}">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label for="goal" class="control-label">مقصد</label>
                            <input type="text" class="form-control" name="goal" id="goal" placeholder="مقصد را وارد کنید" value="{{ $bus->goal }}">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label for="move_date" class="control-label">تاریخ حرکت</label>
                            <input type="date" class="form-control" name="move_date" id="move_date" placeholder="تاریخ را وارد کنید" value="{{ $bus->move_dade }}">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label for="move_time" class="control-label">ساعت حرکت</label>
                            <input type="time" class="form-control" name="move_time" id="move_time" placeholder="ساعت حرکت را وارد کنید" value="{{ $bus->move_time }}">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label for="seat" class="control-label">ظرفیت(نفر) </label>
                            <input type="number" class="form-control" name="seat" id="seat" placeholder="ظرفیت اتوبوس را وارد کنید" value="{{ old('seat') }}">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <label for="cost" class="control-label">مبلغ</label>
                            <input type="number" class="form-control" name="cost" id="cost" placeholder="مبلغ را وارد کنید" value="{{ $bus->cost }}">
                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-danger">ثبت تغییرات</button>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>

@endsection

resources/views/Admin/errors.blade.php
@if(count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/alert.blade.php
@extends('master')

@section('content')

    <div class="text-center my-5">
        <h2>{{  $message }}</h2>
    </div>

    <div class="text-center">
        <a href="/" class="btn badge-info">بازگشت</a>
    </div>

@endsection

resources/views/index.blade.php
@extends('master')

@section('content')

    @php $oldDate = NULL; @endphp

    @foreach($buses as $bus)

            @if($oldDate != $bus->move_date)
                <h4 class="text-info my-3">سرویس های موجود روز {{ $bus->move_date }}</h4>
            @endif

            <div class="card w-100 mb-2">
            @php $reserve = 0; @endphp
            @for ($i = 0 ; $i < count($bus->tickets); $i++)
                @php
                    if ($bus->tickets[$i]['status'] == 1){
                    $reserve += $bus->tickets[$i]['seat_number'];
                   }
                @endphp
            @endfor

            <div class="card-body d-flex">
                <span class="card-link"><span>مبدا: </span> {{ $bus->origin }}</span>
                <span class="card-link"><span>مقصد: </span>{{ $bus->goal }}</span>
                <span class="card-link"><span>تاریخ حرکت: </span>{{ $bus->move_date }}</span>
                <span class="card-link"><span>ساعت حرکت: </span>{{ $bus->move_time }}</span>
                <span class="card-link"><span>تعداد صندلی خالی: </span>{{ $bus->seat - $reserve }}</span>
                <button type="button" class="btn btn-success mr-auto" data-toggle="modal" data-target="#exampleModal" data-whatever="{{ $bus->id }}"> رزرو بلیط </button>
            </div>
        </div>
        @php
            if ($oldDate != $bus->move_date)
                $oldDate = $bus->move_date
        @endphp
    @endforeach
@endsection

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="rtl">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <link href="{{  url('/') }}/css/bootstrap.min.css" type="text/css" rel="stylesheet">

        <style>
            body {text-align: right;}  a {cursor: pointer;}
        </style>
    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="/">میهن نور فراهان</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/">خانه </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" data-toggle="modal" data-target="#staticBackdrop">کنسل کردن بلیط</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/buses">اتوبوس ها</a>
                        </li>
                    </ul>

                </div>
            </nav>
        </header>


        <!-- main body --->
        <div class="container mt-4">

           @yield('content')

        </div>
        <!-- /-- main body --->



        <!-- Modal -->
        <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">لطفا شماره بلیط مورد نظر را وارد نمایید</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form class="form-horizontal" action="/cancel" enctype="multipart/form-data" method="post">
                            {{ csrf_field() }}
                            @include('Admin.errors')
                            <div class="form-group">
                                <label for="ticket_number" class="col-form-label">شماره بلیط:</label>
                                <input type="tel" name="ticket_number" class="form-control" id="ticket_number">
                            </div>
                            <div class="form-group">
                                <label for="phone_number" class="col-form-label">شماره موبایل:</label>
                                <input type="tel" name="phone_number" class="form-control" id="phone_number">
                            </div>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                            <button type="submit" class="btn btn-danger">حذف</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">اطلاعات خود را وارد کنید</h5>
                        <button type="button" class="close mr-auto ml-0" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form class="form-horizontal" action="/tickets" enctype="multipart/form-data" method="post">
                            {{ csrf_field() }}
                            @include('Admin.errors')
                            <div class="form-group">
                                <label for="bus-number" class="col-form-label">شماره اتوبوس:</label>
                                <input readonly type="number" name="bus_id" class="form-control" id="bus-number">
                            </div>
                            <div class="form-group">
                                <label for="name" class="col-form-label">نام:</label>
                                <input type="text" name="name" class="form-control" id="name">
                            </div>
                            <div class="form-group">
                                <label for="family_name" class="col-form-label">نام خانوادگی:</label>
                                <input type="text" name="family_name" class="form-control" id="family_name">
                            </div>
                            <div class="form-group">
                                <label for="phone_number" class="col-form-label">شماره موبایل:</label>
                                <input type="tel" name="phone_number" class="form-control" id="phone_number">
                            </div>
                            <div class="form-group">
                                <label for="seat_number" class="col-form-label">تعداد صندلی:</label>
                                <input type="number" name="seat_number" class="form-control" id="seat_number">
                            </div>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                            <button type="submit" class="btn btn-primary">ارسال</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- /-- Modal -->


        <!-- /-- Scripts -->
        <script src="{{  url('/') }}/js/jquery-3.5.1.min.js" type="text/javascript"></script>
        <script src="{{  url('/') }}/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="{{  url('/') }}/js/script.js" type="text/javascript"></script>
    </body>
</html>

resources/views/ticket.blade.php
@extends('master')

@section('content')

    <!-- main body --->

        <h2 class="my-3">رزو بلیط شما با موفقیت انجام شد</h2>
        <a href="/" class="mb-3">خروج</a>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>شماره بلیط</th>
                    <th>نام</th>
                    <th>نام خانوادگی</th>
                    <th>شماره تماس</th>
                    <th>تعداد صندلی</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ $code['ticket_number'] }}</td>
                    <td>{{ $request->name }}</td>
                    <td>{{ $request->family_name }}</td>
                    <td>{{ $request->phone_number }}</td>
                    <td>{{ $request->seat_number }}</td>
                </tr>
                </tbody>
                <thead>
                <tr>
                    <th>نوع اتوبوس</th>
                    <th>مبدا</th>
                    <th>مقصد</th>
                    <th>تاریخ حرکت</th>
                    <th>ساعت حرکت</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ $bus->type }}</td>
                    <td>{{ $bus->origin }}</td>
                    <td>{{ $bus->goal }}</td>
                    <td>{{ $bus->move_date }}</td>
                    <td>{{ $bus->move_time }}</td>
                </tr>
                </tbody>
            </table>
        </div>


@endsection